quarkus.jackson.serialization-inclusion=non-null

# You can customize your test port
quarkus.http.test-port=8282

# Specify here the Mock URL provided by microcks devservices, referencing the quarkus.microcks.default.http
quarkus.rest-client.pastries.url=${quarkus.microcks.default.http}/rest/API+Pastries/0.0.1

mp.messaging.outgoing.orders-created.connector=smallrye-kafka
mp.messaging.outgoing.orders-created.topic=orders-created

# Specify here the Mock Topic provided by microcks devservices, following the naming convention.
mp.messaging.incoming.orders-reviewed.connector=smallrye-kafka
mp.messaging.incoming.orders-reviewed.topic=OrderEventsAPI-0.1.0-orders-reviewed

quarkus.log.level=INFO
quarkus.log.category."org.testcontainers".level=INFO
quarkus.log.category."tc".level=INFO
